run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - errname
    - errorlint
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
